name: 'mobility_analysis'
version: '1.1.1'
profile: 'mobility_analysis'

model-paths: ["models", "groups"]
docs-paths: ["docs"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  mobility_analysis:
    analytics:
      +materialized: view
      +group: analytics
    consolidate:
      +materialized: incremental
      +incremental_strategy: merge
      +group: consolidate
      +on_schema_change: fail
    staging:
      +materialized: ephemeral
      +group: staging

vars:
  PARIS_CITY_CODE : 1
  NANTES_CITY_CODE : 2
  TOULOUSE_CITY_CODE : 3
  STRASBOURG_CITY_CODE : 4
  BORDEAUX_CITY_CODE : 5
  MARSEILLE_CITY_CODE : 6